controller_manager:
  ros__parameters:
    update_rate: 100 # Frequenza di aggiornamento del Controller Manager 
    
    # Controller sempre attivi
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # Controller per il movimento 
    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
   
    arm_position_controller:
      type: position_controllers/JointGroupPositionController

arm_trajectory_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    command_interfaces:
      - position
      - velocity 
    state_interfaces:
      - position
      - velocity

arm_position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
